### ISSUE TITLE
Create Auth Service (Backend)

### ISSUE THREAD

**Issue by krishnaglick** [krishnaglick/MEEQS_Sane#1]
Need to create a login/register/authentication service on the backend.

**Comment by CygnusRoboticus** [comment]
Require backend to pass back a 401 forbidden whenever attempting to move to a restricted route. This will facilitate redirecting the frontend to a swank-ass login screen.
#6

**Comment by CygnusRoboticus** [comment]
Return something from your logout function. This is on the frontend branch temporarily to resolve logout issues.
https://github.com/krishnaglick/MEEQS_Sane/issues/7
