### ISSUE TITLE
Persist Login

### ISSUE THREAD

**Issue by krishnaglick** [krishnaglick/MEEQS_Sane#17]
Users should not be logged out when navigating away from our site. Ember simple auth should have a way to do this.

**Comment by CygnusRoboticus** [comment]
This require backend modifications as described here: https://github.com/simplabs/ember-simple-auth/tree/master/packages/ember-simple-auth-devise#server-side-setup

Currently the frontend should be setup to handle persisted sessions if a token were provided as described, but additional testing may be required at such a time that functionality is created.

**Comment by krishnaglick** [comment]
https://github.com/simplabs/ember-simple-auth/tree/master/packages/ember-simple-auth-cookie-store
Maybe?

**Comment by CygnusRoboticus** [comment]
Frontend is corrected to handle persisted login, but the backend needs to pass back a token (besides the user model it kicks back now). Let me know if this should instead be the "sails.sid" cookie that's currently being created.

**Comment by krishnaglick** [comment]
Make ember call auth endpoint on page load if token exists.
