### ISSUE TITLE
Unable to create restaurant

### ISSUE THREAD

**Issue by CygnusRoboticus** [krishnaglick/MEEQS_Sane#3]
The following request:
$.ajax({url:"http://localhost:1337/api/v1/restaurants",method:"POST",data:{name:"Wings n Things"}}).done(function(data){console.log(data)});

Yields the following response:
{
  "error": "E_VALIDATION",
  "status": 400,
  "summary": "1 attribute is invalid",
  "model": "Restaurants",
  "invalidAttributes": {
    "name": [
      {
        "rule": "string",
        "message": "`undefined` should be a string (instead of \"null\", which is a object)"
      },
      {
        "rule": "required",
        "message": "\"required\" validation rule failed for input: null"
      }
    ]
  }
}

http://i.imgur.com/3X9IXjo.png

Error may be in DB configuration, as I am (perhaps mistakenly) assuming sane generates my backend for me.

**Comment by krishnaglick** [comment]
Relevant file:
https://github.com/krishnaglick/MEEQS_Sane/blob/master/server/api/models/Restaurants.js

**Comment by krishnaglick** [comment]
So, data needs to be passed in as data:{modelName: {attribute: value}} rather than data:{attribute:value, attribute:value}.

For this issue in particular, do the following.
data: {restaurants:{name: 'Wings n Things'}}
