### ISSUE TITLE
Sideload restaurant-locations on restaurant GET

### ISSUE THREAD

**Issue by CygnusRoboticus** [krishnaglick/MEEQS_Sane#5]
When making a request to /restaurants/:restaurantID, include a collection of restaurant locations along with the current restaurant details.

**Comment by CygnusRoboticus** [comment]
I need to do a bit of research on this first. Ember docs imply this might not be necessary.

**Comment by krishnaglick** [comment]
Roger, lemme know!

**Comment by krishnaglick** [comment]
Restaurants returns null for each matching restaurantLocation. Need to figure out why.

**Comment by CygnusRoboticus** [comment]
Slight misunderstanding on how this needs to work (I blame Django mindset).

{
    'restaurants': [
        {restaurantLocations:[1, 2, 3]
    ]
    'restaurantLocations': [
        {restaurantLocationID: 1},
        {restaurantLocationID: 2},
        {restaurantLocationID: 3},
    ]
}
